title: Dira GeoSystems
description: Dira GeoSystems creates software for producing top quality geodata and the most beautiful maps
url: https://dirageosystems.ch
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - Makefile
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include in the output but don't process
include:
  - prosuite/doc/api
  - prosuite/doc/api/_static



