title: Dira GeoSystems
description: Dira GeoSystems creates software for producing top quality geodata and the most beautiful maps
url: https://dirageosystems.ch
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - Makefile
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - prosuite/doc/api/


## Copy documentation to destination
#keep_files:
#  - prosuite/doc/api
#  - prosuite/doc/api/_static
#
## Additional static file serving
#staticfiles:
#  - prosuite/doc/api/_static
